//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcces
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produccion
    {
        public Produccion()
        {
            this.Inventario = new HashSet<Inventario>();
        }
    
        public decimal ProduccionId { get; set; }
        public decimal RecetaId { get; set; }
        public decimal ProduccionCantidad { get; set; }
        public System.DateTime Produccionfhr { get; set; }
        public string ProduccionUser { get; set; }
        public string ProduccionEstado { get; set; }
    
        public virtual ICollection<Inventario> Inventario { get; set; }
        public virtual Receta Receta { get; set; }
    }
}
