//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcces
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public Producto()
        {
            this.Receta = new HashSet<Receta>();
        }
    
        public decimal ProductoId { get; set; }
        public string ProductoCodigo { get; set; }
        public decimal Productocantidad { get; set; }
        public System.DateTime ProductoFhr { get; set; }
        public string ProductoUser { get; set; }
        public string ProductoEstado { get; set; }
        public decimal ProductoUnidad { get; set; }
        public string ProductoDescripcion { get; set; }
    
        public virtual ICollection<Receta> Receta { get; set; }
    }
}
