//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcces
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receta
    {
        public Receta()
        {
            this.Produccion = new HashSet<Produccion>();
        }
    
        public decimal RecetaId { get; set; }
        public string RecetaCodigo { get; set; }
        public string RecetaUnidad { get; set; }
        public decimal RecetaCantidad { get; set; }
        public decimal MateriaPrimaId { get; set; }
        public System.DateTime RecetaFhr { get; set; }
        public string RecetaUser { get; set; }
        public string RecetaEstado { get; set; }
        public decimal ProductoId { get; set; }
        public string RecetaDescripcion { get; set; }
    
        public virtual MateriaPrima MateriaPrima { get; set; }
        public virtual ICollection<Produccion> Produccion { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
